#!/usr/bin/env bash
#
# generate_host.sh — 엔진 링크 xcconfig 생성 + XcodeGen 으로 Host 프로젝트 생성 (Mac 전용)
# prebuilt/<engine> 존재 여부에 따라 *_LINKED 매크로/헤더/라이브러리/프레임워크 링크를
# starlight_engines.xcconfig 로 자동 생성한다(수동 Xcode 편집 불필요).
#
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
PB="$HERE/prebuilt"
XC="$HERE/starlight_engines.xcconfig"

command -v xcodegen >/dev/null || { echo "error: xcodegen 필요 (brew install xcodegen)"; exit 1; }

SWIFT_COND="\$(inherited)"
GCC_DEFS="\$(inherited)"
HDRS="\$(inherited)"
LIBDIRS="\$(inherited)"
FWDIRS="\$(inherited)"
LDFLAGS="\$(inherited) -ObjC"

# ---- MeloNX (NativeAOT dylib) : Swift @_silgen_name → dylib 링크 ----
if [ -f "$PB/melonx/Ryujinx.Headless.SDL2.dylib" ]; then
  echo "[gen] MeloNX linked"
  SWIFT_COND="$SWIFT_COND MELONX_LINKED"
  LDFLAGS="$LDFLAGS \$(SRCROOT)/prebuilt/melonx/Ryujinx.Headless.SDL2.dylib"
fi

# ---- PPSSPP (정적 라이브러리 다수) : LINK_PPSSPP=1 일 때만 링크(단계적 통합) ----
if [ "${LINK_PPSSPP:-0}" = "1" ] && ls "$PB/ppsspp/"*.a >/dev/null 2>&1; then
  echo "[gen] PPSSPP linked"
  GCC_DEFS="$GCC_DEFS PPSSPP_LINKED=1"
  HDRS="$HDRS \$(SRCROOT)/../01_sources/PPSSPP"
  LIBDIRS="$LIBDIRS \$(SRCROOT)/prebuilt/ppsspp"
  # libPPSSPPCore 를 먼저, 이후 나머지 .a (ld64 는 다중 패스라 순서 민감도 낮음)
  for pref in libPPSSPPCore.a libppsspp_ui.a libCore.a libCommon.a; do
    [ -f "$PB/ppsspp/$pref" ] && LDFLAGS="$LDFLAGS \$(SRCROOT)/prebuilt/ppsspp/$pref"
  done
  for a in "$PB/ppsspp/"*.a; do
    base=$(basename "$a")
    case "$base" in libPPSSPPCore.a|libppsspp_ui.a|libCore.a|libCommon.a) continue;; esac
    LDFLAGS="$LDFLAGS \$(SRCROOT)/prebuilt/ppsspp/$base"
  done
  # PPSSPP iOS 시스템 프레임워크(upstream CMakeLists 기준)
  for fw in Foundation MediaPlayer AudioToolbox CoreGraphics CoreMotion QuartzCore UIKit \
            GLKit OpenAL AVFoundation CoreLocation CoreText CoreVideo CoreMedia CoreServices \
            Metal IOSurface Photos; do
    LDFLAGS="$LDFLAGS -framework $fw"
  done
  LDFLAGS="$LDFLAGS -weak_framework GameController -weak_framework PhotosUI"
  # 시스템 라이브러리: zlib(adler32 등) / bz2 / iconv (ffmpeg·core 요구)
  LDFLAGS="$LDFLAGS -lz -lbz2 -liconv"
  # ffmpeg 하드웨어/미디어 프레임워크
  LDFLAGS="$LDFLAGS -framework VideoToolbox"
fi

# ---- ARMSX2 (정적 라이브러리) : LINK_ARMSX2=1 일 때만 링크 ----
if [ "${LINK_ARMSX2:-0}" = "1" ] && ls "$PB/armsx2/"*.a >/dev/null 2>&1; then
  echo "[gen] ARMSX2 linked"
  GCC_DEFS="$GCC_DEFS ARMSX2_LINKED=1"
  HDRS="$HDRS \$(SRCROOT)/../01_sources/ARMSX2 \$(SRCROOT)/../01_sources/ARMSX2/pcsx2 \$(SRCROOT)/../01_sources/ARMSX2/common"
  LIBDIRS="$LIBDIRS \$(SRCROOT)/prebuilt/armsx2"
  for a in "$PB/armsx2/"*.a; do
    LDFLAGS="$LDFLAGS \$(SRCROOT)/prebuilt/armsx2/$(basename "$a")"
  done
fi

cat > "$XC" <<EOF
// Auto-generated by generate_host.sh — 엔진 링크(수동 편집 금지). prebuilt/ 기준 자동 생성.
SWIFT_ACTIVE_COMPILATION_CONDITIONS = $SWIFT_COND
GCC_PREPROCESSOR_DEFINITIONS = $GCC_DEFS
HEADER_SEARCH_PATHS = $HDRS
LIBRARY_SEARCH_PATHS = $LIBDIRS
FRAMEWORK_SEARCH_PATHS = $FWDIRS
OTHER_LDFLAGS = $LDFLAGS
EOF
echo "[gen] wrote $XC:"; sed 's/^/    /' "$XC"

cd "$HERE"
xcodegen generate
echo "[generate_host] StarlightEmulator.xcodeproj 생성 완료."
